/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import modelos.excepciones.LoginException;

/**
 *
 * @author cferreri
 */
public abstract class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, String titulo) {
        initComponents();
        setLocationRelativeTo(parent);
        
    }
    
    public void cambiarTitulo(String titulo){
        this.lblTextoLogin.setText(titulo);
    }

    
    public abstract Object ejecutarLogin(String usu, String pwd);
    
    public abstract void ejecutarCasoUso(Object obj);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextoLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        btnEjecutarLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTextoLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTextoLogin.setText("Login sistema");

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        btnEjecutarLogin.setText("Iniciar Sesion");
        btnEjecutarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTextoLogin)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(txtUsuario)
                        .addComponent(jLabel2)
                        .addComponent(txtContrasenia)
                        .addComponent(btnEjecutarLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTextoLogin)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnEjecutarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjecutarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarLoginActionPerformed
        this.login();
    }//GEN-LAST:event_btnEjecutarLoginActionPerformed

    private void login()
    {
            String usu = this.txtUsuario.getText();
            String pas = this.txtContrasenia.getText();

            if(usu.isBlank() || pas.isBlank()){
                JOptionPane.showMessageDialog(this,"Debe completar los campos de usuario y contraseña", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                Object resultado = this.ejecutarLogin(usu, pas);
                if(resultado != null){
                    this.ejecutarCasoUso(resultado);
                }
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutarLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTextoLogin;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
